package com.pages.mis;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.support.ui.WebDriverWait;

public class CreateMedicalCard {
    private WebDriver webDriver;
    private WebDriverWait wait;

    public CreateMedicalCard() {
    }

    public void createNewMkab() {
        webDriver.findElement(By.xpath("//div[@id='Portlet_2']/div[2]/div[4]/a/span")).click();
        webDriver.findElement(By.xpath("//button[@id='btnAddMKAB']/span[2]")).click();
        webDriver.findElement(By.id("MKAB_Dlg_Family")).clear();
        webDriver.findElement(By.id("MKAB_Dlg_Family")).sendKeys("123");
        webDriver.findElement(By.id("MKAB_Dlg_Name")).clear();
        webDriver.findElement(By.id("MKAB_Dlg_Name")).sendKeys("123");
        webDriver.findElement(By.id("MKAB_Dlg_Family")).clear();
        webDriver.findElement(By.id("MKAB_Dlg_Family")).sendKeys("имсисмимси");
        webDriver.findElement(By.id("MKAB_Dlg_Name")).clear();
        webDriver.findElement(By.id("MKAB_Dlg_Name")).sendKeys("мсисмимси");
        webDriver.findElement(By.id("MKAB_Dlg_Patronim")).click();
        webDriver.findElement(By.id("MKAB_Dlg_Patronim")).clear();
        webDriver.findElement(By.id("MKAB_Dlg_Patronim")).sendKeys("мсимсисмимс");
        webDriver.findElement(By.id("MKAB_Dlg_BirthDate")).click();
        webDriver.findElement(By.id("MKAB_Dlg_BirthDate")).click();
        webDriver.findElement(By.xpath("//a[@id='MKAB_Dlg_Gender-button']/span")).click();
        webDriver.findElement(By.id("ui-selectmenu-item-342")).click();
        webDriver.findElement(By.id("MKAB_Dlg_SNILS")).click();
        webDriver.findElement(By.xpath("//a[@id='MKAB_Dlg_InvID-button']/span")).click();
        webDriver.findElement(By.id("ui-selectmenu-item-528")).click();
        webDriver.findElement(By.xpath("//a[@id='MKAB_Dlg_SocStatusID-button']/span")).click();
        webDriver.findElement(By.id("ui-selectmenu-item-34")).click();
        webDriver.findElement(By.xpath("//a[@id='MKAB_Dlg_MaterialStatusId-button']/span")).click();
        webDriver.findElement(By.id("ui-selectmenu-item-472")).click();
        webDriver.findElement(By.xpath("//a[@id='MKAB_Dlg_EducationTypeId-button']/span")).click();
        webDriver.findElement(By.id("ui-selectmenu-item-273")).click();
        webDriver.findElement(By.id("mkab_representatives")).click();
        webDriver.findElement(By.xpath("//div[61]/div[3]/div/button/span")).click();
        webDriver.findElement(By.xpath("//a[@id='MKAB_Dlg_SelectedPolis-button-button']/span")).click();
        webDriver.findElement(By.id("mkab_allPolises")).click();
        webDriver.findElement(By.xpath("//div[63]/div[3]/div/button/span")).click();
        webDriver.findElement(By.xpath("//button[@id='MKAB_AddPolisBtn']/span[2]")).click();
        webDriver.findElement(By.id("MKAB_Dlg_PolisFakeModel_SMO_Name")).click();
        webDriver.findElement(By.xpath("(//img[@alt='Выбор'])[11]")).click();
        webDriver.findElement(By.xpath("//tr[@id='1102']/td[3]")).click();
        webDriver.findElement(By.xpath("//div[67]/div[3]/div/button/span")).click();
        webDriver.findElement(By.id("MKAB_Dlg_mkabPolis_Series")).click();
        webDriver.findElement(By.id("MKAB_Dlg_mkabPolis_Series")).clear();
        webDriver.findElement(By.id("MKAB_Dlg_mkabPolis_Series")).sendKeys("1111");
        webDriver.findElement(By.id("mkabPolis_form")).click();
        webDriver.findElement(By.id("MKAB_Dlg_mkabPolis_Number")).click();
        webDriver.findElement(By.id("MKAB_Dlg_mkabPolis_Number")).clear();
        webDriver.findElement(By.id("MKAB_Dlg_mkabPolis_Number")).sendKeys("11111111111");
        webDriver.findElement(By.xpath("//form[@id='mkabPolis_form']/div[3]/div/label/span/span")).click();
        webDriver.findElement(By.xpath("//form[@id='mkabPolis_form']/div[3]/div/label/span/div")).click();
        webDriver.findElement(By.xpath("//a[@id='MKAB_Dlg_PolisFakeModel_ProfitTypeID-button']/span")).click();
        webDriver.findElement(By.id("ui-selectmenu-item-664")).click();
        webDriver.findElement(By.xpath("//a[@id='MKAB_Dlg_PolisFakeModel_PolisTypeID-button']/span")).click();
        webDriver.findElement(By.xpath("//button[@id='MKABPolisDkgSaveButton']/span")).click();
        webDriver.findElement(By.xpath("//div[66]/div[3]/div/button/span")).click();
        webDriver.findElement(By.xpath("//tr[@id='-1']/td[9]")).click();
        webDriver.findElement(By.xpath("//div[3]/div/button[2]/span")).click();
        webDriver.findElement(By.id("MKAB_Dlg_Document_Silent")).click();
        webDriver.findElement(By.xpath("(//img[@alt='Выбор'])[3]")).click();
        webDriver.findElement(By.xpath("//tr[@id='2']/td")).click();
        webDriver.findElement(By.xpath("//tr[@id='3']/td")).click();
        webDriver.findElement(By.xpath("//div[66]/div[3]/div/button/span")).click();
        webDriver.findElement(By.xpath("//div[@id='mkab_document']/fieldset")).click();
        webDriver.findElement(By.id("MKAB_Dlg_SeriesDocument")).click();
        webDriver.findElement(By.id("MKAB_Dlg_SeriesDocument")).clear();
        webDriver.findElement(By.id("MKAB_Dlg_SeriesDocument")).sendKeys("1111");
        webDriver.findElement(By.xpath("//div[@id='mkab_document']/fieldset/div[3]/div")).click();
        webDriver.findElement(By.id("MKAB_Dlg_NumberDocument")).click();
        webDriver.findElement(By.id("MKAB_Dlg_NumberDocument")).clear();
        webDriver.findElement(By.id("MKAB_Dlg_NumberDocument")).sendKeys("111111");
        webDriver.findElement(By.id("MKAB_Dlg_DateDocument")).click();
        webDriver.findElement(By.id("MKAB_Dlg_DateDocument")).click();
        webDriver.findElement(By.id("MKAB_Dlg_DocIssuedBy")).click();
        webDriver.findElement(By.id("MKAB_Dlg_DocIssuedBy")).clear();
        webDriver.findElement(By.id("MKAB_Dlg_DocIssuedBy")).sendKeys("ваиавиавивипави");
        webDriver.findElement(By.xpath("//a[@id='MKAB_Dlg_SpecialCaseID-button']/span")).click();
        webDriver.findElement(By.id("ui-selectmenu-item-408")).click();
        webDriver.findElement(By.id("MKAB_Dlg_MobilePhoneNumber")).click();
        webDriver.findElement(By.id("MKAB_Dlg_Email")).click();
        webDriver.findElement(By.id("MKAB_Dlg_Email")).clear();
        webDriver.findElement(By.id("MKAB_Dlg_Email")).sendKeys("temnikov@email.com");
        webDriver.findElement(By.xpath("//a[@id='MKAB_Dlg_LocationID-button']/span")).click();
        webDriver.findElement(By.id("ui-selectmenu-item-503")).click();
        webDriver.findElement(By.xpath("//div[@id='makbtabs_First']/div/div[18]/div/label/span")).click();
        webDriver.findElement(By.xpath("//div[@id='mkab_tabs']/ul")).click();
        webDriver.findElement(By.linkText("Дополнительно")).click();
        webDriver.findElement(By.xpath("//a[@id='MKAB_Dlg_CitizenID-button']/span")).click();
        webDriver.findElement(By.id("ui-selectmenu-item-77")).click();
        webDriver.findElement(By.id("MKAB_Dlg_BirthPlace")).click();
        webDriver.findElement(By.id("MKAB_Dlg_BirthPlace")).clear();
        webDriver.findElement(By.id("MKAB_Dlg_BirthPlace")).sendKeys("vfghfdhfd");
        webDriver.findElement(By.xpath("//div[@id='makbtabs_Adress']/div/div[3]/label/span/span")).click();
        webDriver.findElement(By.id("MKAB_Dlg_LocationOfWork")).click();
        webDriver.findElement(By.id("MKAB_Dlg_LocationOfWork")).clear();
        webDriver.findElement(By.id("MKAB_Dlg_LocationOfWork")).sendKeys("fgfhdghfhd");
        webDriver.findElement(By.id("MKAB_Dlg_PostOfWork")).click();
        webDriver.findElement(By.id("MKAB_Dlg_PostOfWork")).clear();
        webDriver.findElement(By.id("MKAB_Dlg_PostOfWork")).sendKeys("fgdhgfdhgfdh");
        webDriver.findElement(By.id("MKAB_Dlg_Profession")).click();
        webDriver.findElement(By.id("MKAB_Dlg_Profession")).clear();
        webDriver.findElement(By.id("MKAB_Dlg_Profession")).sendKeys("gdfhgfhdfh");
        webDriver.findElement(By.xpath("(//img[@alt='Выбор'])[5]")).click();
        webDriver.findElement(By.xpath("//tr[@id='13831']/td[2]")).click();
        webDriver.findElement(By.xpath("//div[71]/div[3]/div/button/span")).click();
        webDriver.findElement(By.id("MKAB_Dlg_PhoneHome")).click();
        webDriver.findElement(By.id("MKAB_Dlg_PhoneHome")).clear();
        webDriver.findElement(By.id("MKAB_Dlg_PhoneHome")).sendKeys("fdhgfd");
        webDriver.findElement(By.id("MKAB_Dlg_PhoneWork")).click();
        webDriver.findElement(By.id("MKAB_Dlg_PhoneWork")).clear();
        webDriver.findElement(By.id("MKAB_Dlg_PhoneWork")).sendKeys("fdhgfhdgfhd");
        webDriver.findElement(By.id("MKAB_Dlg_FluorContingentName")).click();
        webDriver.findElement(By.xpath("//div[@id='mkab_fluorCard']/fieldset")).click();
        webDriver.findElement(By.xpath("(//img[@alt='Выбор'])[6]")).click();
        webDriver.findElement(By.xpath("(//tr[@id='7']/td[2])[2]")).click();
        webDriver.findElement(By.xpath("(//tr[@id='8']/td[2])[2]")).click();
        webDriver.findElement(By.xpath("//div[74]/div[3]/div")).click();
        webDriver.findElement(By.xpath("//div[74]/div[3]/div/button/span")).click();
        webDriver.findElement(By.xpath("(//img[@alt='Выбор'])[7]")).click();
        webDriver.findElement(By.xpath("(//tr[@id='5']/td[2])[2]")).click();
        webDriver.findElement(By.xpath("//div[75]/div[3]/div/button/span")).click();
        webDriver.findElement(By.xpath("//span/label/span/span")).click();
        webDriver.findElement(By.xpath("//button[@id='btn_save_schedule']/span")).click();
        webDriver.findElement(By.linkText("Пациент")).click();
        webDriver.findElement(By.xpath("//div[@id='makbtabs_First']/div/div[15]/fieldset/div/div/a/img")).click();
        webDriver.findElement(By.id("ui-active-menuitem")).click();
        webDriver.findElement(By.id("house_MKAB_Dlg_RegistrationAdressID")).click();
        webDriver.findElement(By.id("house_MKAB_Dlg_RegistrationAdressID")).clear();
        webDriver.findElement(By.id("house_MKAB_Dlg_RegistrationAdressID")).sendKeys("gfgd");
        webDriver.findElement(By.id("street_MKAB_Dlg_RegistrationAdressID")).click();
        webDriver.findElement(By.id("street_MKAB_Dlg_RegistrationAdressID")).clear();
        webDriver.findElement(By.id("street_MKAB_Dlg_RegistrationAdressID")).sendKeys("fhfdghfdhgfd");
        webDriver.findElement(By.id("house_MKAB_Dlg_RegistrationAdressID")).click();
        webDriver.findElement(By.id("house_MKAB_Dlg_RegistrationAdressID")).clear();
        webDriver.findElement(By.id("house_MKAB_Dlg_RegistrationAdressID")).sendKeys("ghd");
        webDriver.findElement(By.id("street_MKAB_Dlg_RegistrationAdressID")).click();
        webDriver.findElement(By.xpath("//div[2]/label/span/span")).click();
        webDriver.findElement(By.id("street_MKAB_Dlg_RegistrationAdressID")).click();
        webDriver.findElement(By.id("street_MKAB_Dlg_RegistrationAdressID")).clear();
        webDriver.findElement(By.id("street_MKAB_Dlg_RegistrationAdressID")).sendKeys("fgbdghd");
        webDriver.findElement(By.id("house_MKAB_Dlg_RegistrationAdressID")).click();
        webDriver.findElement(By.id("street_MKAB_Dlg_RegistrationAdressID")).click();
        webDriver.findElement(By.xpath("//button[@id='btnnotfount_MKAB_Dlg_RegistrationAdressID']/span")).click();
        webDriver.findElement(By.id("textaddr")).clear();
        webDriver.findElement(By.id("textaddr")).sendKeys("Московская обл, Подольск гdfgdgfdgdg");
        webDriver.findElement(By.xpath("//div[78]/div[3]/div/button/span")).click();
        webDriver.findElement(By.xpath("//div[77]/div[3]/div/button/span")).click();
        webDriver.findElement(By.xpath("//button[@id='btn_save_schedule']/span")).click();
        webDriver.findElement(By.xpath("//div[77]/div[3]/div/button/span")).click();
        webDriver.findElement(By.id("MKAB_Dlg_SNILS")).click();
        webDriver.findElement(By.id("MKAB_Dlg_SNILS")).clear();
        webDriver.findElement(By.id("MKAB_Dlg_SNILS")).sendKeys("743-691-356 24");
        webDriver.findElement(By.xpath("//button[@id='mkabDlgPrintButton']/span")).click();
        webDriver.findElement(By.xpath("//div[78]/div[3]/div/button/span")).click();
        // ERROR: Caught exception [ERROR: Unsupported command [selectWindow | win_ser_1 | ]]
        // ERROR: Caught exception [ERROR: Unsupported command [selectWindow | win_ser_local | ]]
        // ERROR: Caught exception [ERROR: Unsupported command [selectWindow | win_ser_1 | ]]
        webDriver.findElement(By.xpath("//div[@id='main']/table/tbody/tr[3]/td/b/u/i")).click();
        webDriver.findElement(By.xpath("//div[@id='main']/table/tbody/tr[10]/td/table/tbody/tr/td[3]")).click();
        webDriver.findElement(By.xpath("//div[@id='main']/table/tbody/tr[11]/td/table/tbody/tr/td[3]")).click();
        webDriver.findElement(By.xpath("//div[@id='main']/table/tbody/tr[17]/td/table/tbody/tr/td[3]")).click();
        webDriver.findElement(By.xpath("//div[@id='main']/table/tbody/tr[20]/td/table/tbody/tr/td[3]")).click();
        // ERROR: Caught exception [ERROR: Unsupported command [selectWindow | win_ser_local | ]]
        webDriver.findElement(By.xpath("//button[@id='btn_save_schedule']/span")).click();
        webDriver.findElement(By.xpath("//div[78]/div[3]/div/button/span")).click();
        webDriver.findElement(By.xpath("//tr[@id='2602803']/td[3]")).click();
        webDriver.findElement(By.xpath("//tr[@id='2602803']/td[5]")).click();
        webDriver.findElement(By.xpath("//tr[@id='2602803']/td[6]")).click();
        webDriver.findElement(By.xpath("//tr[@id='2602803']/td[8]")).click();
        webDriver.findElement(By.xpath("(//span[@value='{\"Id\":0,\"Name\":\"Московская обл, Подольск гdfgdgfdgdg\",\"Guid\":\"00000000-0000-0000-0000-000000000000\"}'])[2]")).click();
    }
}
